name: acentu.ar CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - uses: actions/checkout@master

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          version: 16.x
          cache: "pnpm"
      
      - name: Installing frozen lock-file
        run: pnpm install --frozen-lockfile
      
      # - name: Testing the proyect
      #   run: pnpm playwright test
      
      - name: Building the proyect
        run: pnpm build

      - name: Copying the files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: "${{secrets.SSHKEY}}"
          source: "./.svelte-kit"
          target: "./acentu.ar/"
          strip_components: 2
          rm: true



        